# This will be used to create a new instance of the container and pushes it to Dockerhub, rightgit 

name: Python Flask App CI

on:
  push:
    branches:
      - main
  #pull_request:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authentication credentials of dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB }}

      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r webapp/requirements.txt

    - name: Run Flask app
      run: |
        python webapp/app.py &
        sleep 5  # Wait for the server to start

    - name: Run tests (if you have any)
      run: |
        # Add your test command here, for example:
        # pytest tests/
        echo "Tests could be run here"

    - name: Check for linter errors (optional)
      run: |
        pip install flake8
        flake8 webapp/app.py

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
      id: buildx

    - name: build flask app and push dockerhub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: mtabak1907/flask-app:latest