name: Python Flask App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r webapp/requirements.txt

    - name: Run Flask app
      run: |
        python webapp/app.py &
        sleep 5  # Wait for the server to start

    - name: Run tests (if you have any)
      run: |
        # Add your test command here, for example:
        # pytest tests/
        echo "Tests could be run here"

    - name: Check for linter errors (optional)
      run: |
        pip install flake8
        flake8 webapp/app.py

    - name: Hadolint Action
      uses: hadolint/hadolint-action@v3.1.0
            
